[package]
name = "rust-polars-csv-dataframe-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.40.0", features = ["lazy"] }
regex = "1.10.5"
reqwest = { version = "0.12.4", features = ["json","blocking"] }